@LinkDev.Talabat.APIs_HostAddress = https://localhost:7045

GET {{LinkDev.Talabat.APIs_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{LinkDev.Talabat.APIs_HostAddress}}/api/weatherforecast

###
